### PR TITLE
add nodemon to deps list

### PR DESCRIPTION
**Pull request by aintgoin2goa**
`nbt run --watch` uses this but it's not actually required..

### CODE REVIEW

**Comment by matthew-andrews** [comment]
:+1:

**Comment by matthew-andrews** [comment]
oops :innocent:

**Comment by matthew-andrews** [comment]
actually this might not work

**Comment by matthew-andrews** [comment]
i don't think the `bin` scripts of dependencies get created…

**Comment by matthew-andrews** [comment]
i think we'd need to use this:-
https://github.com/remy/nodemon/blob/master/doc/requireable.md

and basically copy the contents of this into NBT
https://github.com/remy/nodemon/blob/master/bin/nodemon.js

and add `nodemon` to `package.json` scripts https://github.com/Financial-Times/next-build-tools/blob/master/package.json#L4-L7

**Comment by aintgoin2goa** [comment]
I'm confused.  Surely the first link tells us that we don't need the other 2 things??

We would just require nodemon and run it there and then...

The other alternative is to require it to be installed globally...

**Comment by matthew-andrews** [comment]
The first option might work… worth trying… we might need to do something to isolate the two `nodemon`s that will be run (the local app and the router app) from each other though.

**Comment by aintgoin2goa** [comment]
I don't know what this is anymore, but it's probably stale.  Closing...

**Pull request closed without merging**
