### PR TITLE
Fix source maps

### PR DESCRIPTION
**Pull request by ironsidevsquincy**
Previously we minified the JS within NBT, and pulled the source map out from an inline comment into an external file. This is now broken, e.g. the source map created looks like

```
{"version":3,"file":"main.js","sources":[],"names":[],"mappings":"","sourceRoot":"/source/","sourcesContent":[]}
```

However OBT4 has fixed the issue with minifying and creating a source map, so suggest we let OBT do its thing, inline the source map, and look at pulling it into another file in a future PR

### CODE REVIEW

**Comment by ironsidevsquincy** [comment]
https://github.com/Financial-Times/origami-build-tools/issues/315

**Comment by matthew-andrews** [comment]
won't this make our js files rather big?

**Comment by ironsidevsquincy** [comment]
yes, but as we don't have working sourcemaps right now, better that than none.

**Comment by keirog** [comment]
Another good use case for staging

**Comment by matthew-andrews** [comment]
@keirog staging?

**Comment by keirog** [comment]
Was a silly comment really, but I meant a staging environment with inline source maps (+ not included in prod)

**Comment by wheresrhys** [comment]
OBT fix https://github.com/Financial-Times/origami-build-tools/pull/323

**Pull request merged**
