### PR TITLE
Don't keep hitting a failing URL

### PR DESCRIPTION
**Pull request by i-like-robots**
@ironsidevsquincy @imranolas

### CODE REVIEW

**Comment by ironsidevsquincy** [comment]
:+1:

**Comment by matthew-andrews** [comment]
we should totally start writing some tests for this

**Comment by wheresrhys** [comment]
Maybe only exit after n failures, where n is a fairly low number, otherwise if a url fails for a spurious reason (network failure?) the build will fail without a retry.

So this PR but also replace fetch with eager fetch? @i-like-robots

**Comment by ironsidevsquincy** [comment]
I'm for keeping it simple initially, don't retry, and if we find the we are getting false negatives (network blips, etc) then implementing a retry

**Comment by i-like-robots** [comment]
If we do decide to implement a retry we should also throttle it because these are only little dynos with a limited amount of memory.

**Pull request merged**
