### PR TITLE
Pick a standard for function () vs. function()

### PR DESCRIPTION
**Pull request by matthew-andrews**
@wheresrhys

### CODE REVIEW

**Comment by ironsidevsquincy** [comment]
Boooooo

```{"anonymous": "always", "named": "never"}```

cf: http://javascript.crockford.com/code.html#function

**Comment by matthew-andrews** [comment]
is that a vote for #270 darren @ironsidevsquincy 
?

**Comment by ironsidevsquincy** [comment]
democratic pull requests

**Comment by charypar** [comment]
:+1:

**Pull request closed without merging**
