### PR TITLE
Add --serves option to rebuild

### PR DESCRIPTION
**Pull request by imranolas**
Trigger rebuilds for apps based on the `serves` property listed in the `next-registry`. Useful for rebuilding a subset of apps upon release of a shared component.

### CODE REVIEW

**Comment by matthew-andrews** [comment]
```
mandrews@ft-mw4284 ~/sandboxes/next-build-tools (rebuild-serves) $ cd ../next-article
mandrews@ft-mw4284 ~/sandboxes/next-article (master) $ :
mandrews@ft-mw4284 ~/sandboxes/next-article (master) $ ../next-build-tools/bin/next-build-tools.js download-development-keys
^C
mandrews@ft-mw4284 ~/sandboxes/next-article (master) $ ../next-build-tools/bin/next-build-tools.js  rebuild --serves api
Considering whether to rebuild next-concepts-api
Considering whether to rebuild next-myft-api
Considering whether to rebuild next-personalised-feed-api
Considering whether to rebuild next-harrier
Considering whether to rebuild next-brightcove-proxy-api
Considering whether to rebuild next-ab
Considering whether to rebuild next-spoor-ingest
Clearing cache and triggering rebuild of last master build of next-brightcove-proxy-api (Darren Hurley: Merge pull request #34 from Financial-Times/use-view-bertha)
Clearing cache and triggering rebuild of last master build of next-spoor-ingest (Patrick Hamann: Merge pull request #34 from Financial-Times/user-history)
Clearing cache and triggering rebuild of last master build of next-ab (Rhys Evans: enabling test-urls)
Clearing cache and triggering rebuild of last master build of next-harrier (Rhys Evans: Merge pull request #116 from Financial-Times/item-search)
Clearing cache and triggering rebuild of last master build of next-concepts-api (Matt Andrews: update next express)
Clearing cache and triggering rebuild of last master build of next-personalised-feed-api (Arjun Gadhia: Merge pull request #21 from Financial-Times/fresher-content)
Clearing cache and triggering rebuild of last master build of next-myft-api (Arjun Gadhia: Even more logs)
Skipped rebuild of next-myft-api probably because Circle CI not set up for this repo
```

**Comment by charypar** [comment]
@imranolas @matthew-andrews you just gave me a gift of free weekend :) thanks!

**Comment by matthew-andrews** [comment]
@phamann will be happy too :)

**Comment by matthew-andrews** [comment]
don't forget to make a [release](https://github.com/financial-times/next-build-tools/releases)

**Pull request merged**
