### PR TITLE
Android Nexus 7HD in nw config

### PR DESCRIPTION
**Pull request by spriggsha**
Emulates stock browser (default on HTC and Samsung devices) which currently fails js-success test.

@matthew-andrews @commuterjoy

### CODE REVIEW

**Comment by matthew-andrews** [comment]
do you want to add that to the default `env` config too so that it's used on each build?

**Comment by spriggsha** [comment]
@matthew-andrews Yes.  If we're killing builds by supporting extra browsers, this is the way to do it.

**Comment by matthew-andrews** [comment]
@spriggsha that will need updating in this repo now :)
https://github.com/Financial-Times/next-build-tools/blob/master/tasks/nightwatch.js#L13

**Comment by matthew-andrews** [comment]
:+1:

**Pull request merged**
