### PR TITLE
Pick a standard for function () vs. function()

### PR DESCRIPTION
**Pull request by matthew-andrews**
@wheresrhys

### CODE REVIEW

**Comment by ironsidevsquincy** [comment]
Vote for amendment:

{"anonymous": "always", "named": "never"}

cf: http://javascript.crockford.com/code.html#function

**Comment by keirog** [comment]
:+1:

**Comment by matthew-andrews** [comment]
wait so:-

```js
module.exports = function() {
  myfunc();
};

function myfunc() {
  alert("yup i'm using an alert");
}
```

is bad?

and this is good?

```js
var myfunc = function() {
  alert("yup i'm using an alert");
};

module.exports = function() {
  myfunc();
};
```

**Comment by ironsidevsquincy** [comment]
### Bad
```
function() {
    ...
}

function foo () {
   ...
}
```

### Good
```
function () {
    ...
}

function foo() {
   ...
}
```

**Comment by matthew-andrews** [comment]
What's wrong with:-

```js
function foo() {
}

function() {
}
```

**Comment by matthew-andrews** [comment]
My eyes see the inconsistency next the brackets (there should also be text up against the `(`) … and `function() { }` + `function foo() { }` feels the tightest… least wasteful extra characters…

**Comment by ironsidevsquincy** [comment]
To quote DC, "If a function literal is anonymous, there should be one space between the word function and the ( (left parenthesis). If the space is omitted, then it can appear that the function's name is function, which is an incorrect reading."

Which seems a valid reason to do it.

**Pull request merged**
