### PR TITLE
Enforce usage of next-config-vars service by breaking deploys if not used

### PR DESCRIPTION
**Pull request by matthew-andrews**
Up to you @commuterjoy (& team).  I had this in before but took it out because I didn't want to disrupt people.

### CODE REVIEW

**Comment by commuterjoy** [comment]
I vote yes. But how complete/correct is the config-vars set of configs? It looks to be missing quite a few.

**Comment by matthew-andrews** [comment]
So yeah it would break every build… encouraging those vars to be filled out quickly — quite disruptive though!  But good to spread the knowledge of how it works..

**Comment by commuterjoy** [comment]
That's fine, but need to make sure it won't delete vars that people have added in last couple of weeks!

Maybe throw an error rather than delete vars for a week.

**Comment by matthew-andrews** [comment]
hmm…  i don't mind manually checking the ones that are in config-vars (there's only a handful)

**Comment by commuterjoy** [comment]
ok - perhaps i'll pick on someone to add the rest next week, then merge this.

**Comment by commuterjoy** [comment]
I wonder if this is overloading deploy and that Makefile could keep these things separate...

```
next-build-tools provision ft-next-foo
next-build-tools configure ft-next-engels ft-next-foo 
next-build-tools deploy ft-next-foo
```

**Comment by commuterjoy** [comment]
http://git.svc.ft.com:8080/projects/NEXTPRIVATE/repos/config-vars/browse - all env vars are now in the api

**Comment by matthew-andrews** [comment]
i like the solution we currently have, separation of concerns etc.

**Pull request closed without merging**
