### PR TITLE
using curl to test redirects in order to get no-follow

### PR DESCRIPTION
**Pull request by wheresrhys**

### CODE REVIEW

**Comment by matthew-andrews** [comment]
wait

**Comment by matthew-andrews** [comment]
probably obvious but why can't use `follow: 0` here?
https://github.com/bitinn/node-fetch#options

**Comment by wheresrhys** [comment]
Had this chat before. node-fetch/fetch/request all have the behaviour that they're fine up until you hit the redirect limit, but then error as soon as you hit it, so you can't read a 302 response without following it

**Comment by matthew-andrews** [comment]
ah yes sorry

**Comment by matthew-andrews** [comment]
:+1:

**Pull request merged**
